-- Kanoox#9999 
-- #Version 2.0 : Bonta corrigé /🆗
-- #Version 2.1 Brâkmar corrigé /🆗

function brakmarr()
    global:clickPosition(639, 385)
end

function brakmarrr()
    global:clickPosition(389, 25)
end

function move()
    return {
        { map = "5,-18", changeMap = "left" }, 
        { map = "4,-18", changeMap = "left" }, 
        { map = "3,-18", changeMap = "left" }, 
        { map = "2,-18", changeMap = "left" }, 
        { map = "1,-18", changeMap = "left" }, 
        { map = "0,-18", changeMap = "left" }, 
        { map = "-1,-18", changeMap = "left" }, 
        { map = "-2,-18", changeMap = "left" }, 
        { map = "-3,-18", changeMap = "left" }, 
        { map = "-4,-18", changeMap = "left" }, 
        { map = "-5,-18", changeMap = "top" }, 
        { map = "-5,-19", changeMap = "top" }, 
        { map = "-5,-20", changeMap = "top" }, 
        { map = "-5,-21", changeMap = "top" }, 
        { map = "-5,-22", changeMap = "top" }, 
        { map = "-4,-23", changeMap = "right" }, 
        { map = "-5,-23", changeMap = "right" }, 
        { map = "-3,-23", changeMap = "right" }, 
        { map = "-2,-23", changeMap = "right" }, 
        { map = "-1,-23", changeMap = "right" }, 
        { map = "0,-23", changeMap = "right" }, 
        { map = "1,-23", changeMap = "right" }, 
        { map = "2,-23", changeMap = "right" }, 
        { map = "3,-23", changeMap = "right" }, 
        { map = "4,-23", changeMap = "top" }, 
        { map = "4,-24", changeMap = "top" }, 
        { map = "4,-25", changeMap = "top" }, 
        { map = "4,-26", changeMap = "right" }, 
        { map = "5,-26", changeMap = "top" }, 
        { map = "5,-27", changeMap = "top" }, 
        { map = "5,-28", changeMap = "top" }, 
        { map = "5,-29", changeMap = "top" }, 
        { map = "5,-30", changeMap = "top" }, 
        { map = "4,-31", changeMap = "left" }, 
        { map = "5,-31", changeMap = "left" }, 
        { map = "3,-31", changeMap = "top" }, 
        { map = "3,-32", changeMap = "left" }, 
        { map = "2,-32", changeMap = "left" }, 
        { map = "1,-32", changeMap = "left" }, 
        { map = "0,-32", changeMap = "bottom" }, 
        { map = "-1,-31", changeMap = "bottom" }, 
        { map = "-2,-30", changeMap = "bottom" }, 
        { map = "-2,-29", changeMap = "bottom" }, 
        { map = "0,-31", changeMap = "left" }, 
        { map = "-1,-30", changeMap = "left" }, 
        { map = "-2,-28", changeMap = "left" }, 
        { map = "-3,-28", changeMap = "left" }, 
        { map = "-4,-28", changeMap = "left" }, 
        { map = "-5,-28", changeMap = "top" }, 
        { map = "-5,-29", changeMap = "top" }, 
        { map = "-5,-30", changeMap = "top" }, 
        { map = "-5,-31", changeMap = "top" }, 
        { map = "-5,-32", changeMap = "top" }, 
        { map = "-5,-33", changeMap = "top" }, 
        { map = "-5,-34", changeMap = "top" }, 
        { map = "-5,-35", changeMap = "right" }, 
        { map = "-4,-35", changeMap = "top" }, 
        { map = "-4,-36", changeMap = "top" }, 
        { map = "-4,-37", changeMap = "top" }, 
        { map = "-4,-38", changeMap = "right" }, 
        { map = "-3,-38", changeMap = "top" }, 
        { map = "-3,-39", changeMap = "top" }, 
        { map = "-3,-40", changeMap = "top" }, 
        { map = "-3,-41", changeMap = "top" }, 
        { map = "-3,-42", changeMap = "top" }, 
        { map = "-3,-43", changeMap = "top" }, 
        { map = "-3,-44", changeMap = "top" }, 
        { map = "-3,-45", changeMap = "top" }, 
        { map = "-3,-46", changeMap = "top" }, 
        { map = "-3,-47", changeMap = "top" }, 
        { map = "-3,-48", changeMap = "top" }, 
        { map = "-3,-49", changeMap = "top" }, 
        { map = "-11,-50", changeMap = "left" }, 
        { map = "-10,-50", changeMap = "left" }, 
        { map = "-9,-50", changeMap = "left" }, 
        { map = "-8,-50", changeMap = "left" }, 
        { map = "-7,-50", changeMap = "left" }, 
        { map = "-6,-50", changeMap = "left" }, 
        { map = "-5,-50", changeMap = "left" }, 
        { map = "-4,-50", changeMap = "left" }, 
        { map = "-3,-50", changeMap = "left" }, 
        { map = "-12,-50", changeMap = "left" }, 
        { map = "-13,-50", changeMap = "left" }, 
        { map = "-14,-50", changeMap = "left" }, 
        { map = "-15,-50", changeMap = "bottom" }, 
        { map = "-15,-49", changeMap = "bottom" }, 
        { map = "-15,-48", changeMap = "bottom" }, 
        { map = "-15,-47", changeMap = "left" }, 
        { map = "-16,-47", changeMap = "left" }, 
        { map = "-17,-47", changeMap = "left" }, 
        { map = "-18,-47", changeMap = "top" }, 
        { map = "-18,-48", changeMap = "left" }, 
        { map = "-19,-48", changeMap = "left" }, 
        { map = "-20,-48", changeMap = "left" }, 
        { map = "-21,-48", changeMap = "top" }, 
        { map = "-21,-49", changeMap = "top" }, 
        { map = "-21,-50", changeMap = "left" }, 
        { map = "-22,-50", changeMap = "top" }, 
        { map = "-22,-51", changeMap = "top" }, 
        { map = "-22,-52", changeMap = "top" }, 
        { map = "-22,-53", changeMap = "top" }, 
        { map = "-22,-54", changeMap = "left" }, 
        { map = "-23,-54", changeMap = "left" }, 
        { map = "-24,-54", changeMap = "top" }, 
        { map = "-24,-55", changeMap = "top" }, 
        { map = "-37,-55", changeMap = "right" }, 
        { map = "-36,-54", changeMap = "right" }, 
        { map = "-29,-48", changeMap = "bottom" }, 
        { map = "-29,-47", changeMap = "bottom" }, 
        { map = "-29,-46", changeMap = "bottom" }, 
        { map = "-29,-45", changeMap = "bottom" }, 
        { map = "-29,-44", changeMap = "bottom" }, 
        { map = "-29,-43", changeMap = "right" }, 
        { map = "-28,-43", changeMap = "bottom" }, 
        { map = "-28,-42", changeMap = "right" }, 
        { map = "-27,-42", changeMap = "bottom" }, 
        { map = "-27,-41", changeMap = "bottom" }, 
        { map = "-27,-40", changeMap = "bottom" }, 
        { map = "-27,-39", changeMap = "bottom" }, 
        { map = "-27,-38", changeMap = "bottom" }, 
        { map = "-27,-37", changeMap = "bottom" }, 
        { map = "-27,-36", changeMap = "right" }, 
        { map = "-26,-36", changeMap = "right" }, 
        { map = "-25,-36", changeMap = "right" }, 
        { map = "-24,-36", changeMap = "right" }, 
        { map = "-23,-36", changeMap = "right" }, 
        { map = "-22,-36", changeMap = "right" }, 
        { map = "-21,-36", changeMap = "right" }, 
        { map = "-20,-36", changeMap = "right" }, 
        { map = "-19,-36", changeMap = "bottom" }, 
        { map = "-19,-34", changeMap = "bottom" }, 
        { map = "-19,-35", changeMap = "bottom" }, 
        { map = "-19,-33", changeMap = "bottom" }, 
        { map = "-19,-32", changeMap = "bottom" }, 
        { map = "-19,-31", changeMap = "left" }, 
        { map = "-20,-31", changeMap = "bottom" }, 
        { map = "-20,-30", changeMap = "bottom" }, 
        { map = "-20,-29", changeMap = "bottom" }, 
        { map = "-20,-28", changeMap = "bottom" }, 
        { map = "-20,-27", changeMap = "bottom" }, 
        { map = "-20,-26", changeMap = "bottom" }, 
        { map = "-20,-25", changeMap = "bottom" }, 
        { map = "-20,-24", changeMap = "bottom" }, 
        { map = "-20,-23", changeMap = "bottom" }, 
        { map = "-20,-22", changeMap = "bottom" }, 
        { map = "-20,-21", changeMap = "bottom" }, 
        { map = "-20,-20", changeMap = "right" }, 
        { map = "-19,-20", changeMap = "right" }, 
        { map = "-18,-20", changeMap = "right" }, 
        { map = "-17,-20", changeMap = "right" }, 
        { map = "-16,-20", changeMap = "right" }, 
        { map = "-15,-20", changeMap = "right" }, 
        { map = "-14,-20", changeMap = "top" }, 
        { map = "-14,-21", changeMap = "top" }, 
        { map = "-14,-22", changeMap = "top" }, 
        { map = "-14,-23", changeMap = "top" }, 
        { map = "-14,-24", changeMap = "top" }, 
        { map = "-14,-25", changeMap = "top" }, 
        { map = "-14,-26", changeMap = "top" }, 
        { map = "-14,-27", changeMap = "top" }, 
        { map = "-14,-28", changeMap = "right" }, 
        { map = "-13,-28", changeMap = "bottom" }, 
        { map = "-13,-27", changeMap = "bottom" }, 
        { map = "-13,-26", changeMap = "bottom" }, 
        { map = "-13,-25", changeMap = "bottom" }, 
        { map = "-13,-24", changeMap = "bottom" }, 
        { map = "-13,-23", changeMap = "bottom" }, 
        { map = "-13,-22", changeMap = "bottom" }, 
        { map = "-13,-21", changeMap = "bottom" }, 
        { map = "-13,-20", changeMap = "bottom" }, 
        { map = "-13,-19", changeMap = "left" }, 
        { map = "-14,-19", changeMap = "left" }, 
        { map = "-15,-19", changeMap = "left" }, 
        { map = "-16,-19", changeMap = "left" }, 
        { map = "-17,-19", changeMap = "bottom" }, 
        { map = "-17,-18", changeMap = "bottom" }, 
        { map = "-17,-17", changeMap = "bottom" }, 
        { map = "-17,-16", changeMap = "bottom" }, 
        { map = "-17,-15", changeMap = "bottom" }, 
        { map = "-18,-13", changeMap = "bottom" }, 
        { map = "-18,-12", changeMap = "bottom" }, 
        { map = "-18,-14", changeMap = "bottom" }, 
        { map = "-17,-14", changeMap = "left" }, 
        { map = "-18,-11", changeMap = "bottom" }, 
        { map = "-18,-10", changeMap = "bottom" }, 
        { map = "-18,-9", changeMap = "bottom" }, 
        { map = "-18,-8", changeMap = "right" }, 
        { map = "-17,-8", changeMap = "bottom" }, 
        { map = "-17,-7", changeMap = "bottom" }, 
        { map = "-17,-6", changeMap = "bottom" }, 
        { map = "-17,-5", changeMap = "bottom" }, 
        { map = "-17,-4", changeMap = "bottom" }, 
        { map = "-17,-3", changeMap = "right" }, 
        { map = "-16,-3", changeMap = "bottom" }, 
        { map = "-16,-2", changeMap = "bottom" }, 
        { map = "-16,-1", changeMap = "bottom" }, 
        { map = "-16,0", changeMap = "bottom" }, 
        { map = "-16,1", changeMap = "left" }, 
        { map = "-17,1", changeMap = "left" }, 
        { map = "-18,1", changeMap = "left" }, 
        { map = "-19,1", changeMap = "left" }, 
        { map = "-20,1", changeMap = "left" }, 
        { map = "-21,1", changeMap = "left" }, 
        { map = "-22,0", changeMap = "top" }, 
        { map = "-22,1", changeMap = "top" }, 
        { map = "-22,-1", changeMap = "left" }, 
        { map = "-23,-1", changeMap = "left" }, 
        { map = "-24,-1", changeMap = "left" }, 
        { map = "-25,-1", changeMap = "left" }, 
        { map = "-26,-1", changeMap = "bottom" }, 
        { map = "-26,0", changeMap = "bottom" }, 
        { map = "-26,1", changeMap = "bottom" }, 
        { map = "-26,2", changeMap = "bottom" }, 
        { map = "-26,3", changeMap = "bottom" }, 
        { map = "-26,4", changeMap = "bottom" }, 
        { map = "-26,5", changeMap = "bottom" }, 
        { map = "-26,6", changeMap = "bottom" }, 
        { map = "-26,7", changeMap = "bottom" }, 
        { map = "-26,8", changeMap = "bottom" }, 
        { map = "-26,9", changeMap = "bottom" }, 
        { map = "-26,10", changeMap = "bottom" }, 
        { map = "-26,11", changeMap = "right" }, 
        { map = "-25,11", changeMap = "bottom" }, 
        { map = "-25,13", changeMap = "bottom" }, 
        { map = "-25,14", changeMap = "right" }, 
        { map = "-24,14", changeMap = "right" }, 
        { map = "-23,14", changeMap = "right" }, 
        { map = "-22,14", changeMap = "bottom" }, 
        { map = "-22,15", changeMap = "bottom" }, 
        { map = "-22,16", changeMap = "bottom" }, 
        { map = "-22,17", changeMap = "bottom" }, 
        { map = "-22,18", changeMap = "bottom" }, 
        { map = "-22,19", changeMap = "bottom" }, 
        { map = "-22,20", changeMap = "right" }, 
        { map = "-21,20", changeMap = "right" }, 
        { map = "-20,24", changeMap = "left" }, 
        { map = "-21,24", changeMap = "bottom" }, 
        { map = "-21,25", changeMap = "bottom" }, 
        { map = "-21,26", changeMap = "left" }, 
        { map = "-22,26", changeMap = "bottom" }, 
        { map = "-24,28", changeMap = "bottom" }, 
        { map = "-25,29", changeMap = "bottom" }, 
        { map = "-25,30", changeMap = "bottom" }, 
        { map = "-24,29", changeMap = "left" }, 
        { map = "-18,23", changeMap = "right" }, 
        { map = "-17,23", changeMap = "right" }, 
        { map = "-16,23", changeMap = "right" }, 
        { map = "-15,23", changeMap = "right" }, 
        { map = "-14,23", changeMap = "right" }, 
        { map = "-13,23", changeMap = "right" }, 
        { map = "-12,23", changeMap = "right" }, 
        { map = "-11,23", changeMap = "bottom" }, 
        { map = "-10,24", changeMap = "bottom" }, 
        { map = "-10,25", changeMap = "right" }, 
        { map = "-9,26", changeMap = "right" }, 
        { map = "-8,26", changeMap = "right" }, 
        { map = "-7,26", changeMap = "right" }, 
        { map = "-6,26", changeMap = "right" }, 
        { map = "-5,26", changeMap = "right" }, 
        { map = "-4,26", changeMap = "right" }, 
        { map = "-3,26", changeMap = "right" }, 
        { map = "-2,26", changeMap = "top" }, 
        { map = "-2,25", changeMap = "top" }, 
        { map = "-2,24", changeMap = "right" }, 
        { map = "-1,24", changeMap = "right" }, 
        { map = "0,24", changeMap = "right" }, 
        { map = "1,24", changeMap = "bottom" }, 
        { map = "2,25", changeMap = "bottom" }, 
        { map = "2,26", changeMap = "bottom" }, 
        { map = "1,25", changeMap = "right" }, 
        { map = "2,27", changeMap = "right" }, 
        { map = "3,27", changeMap = "right" }, 
        { map = "4,29", changeMap = "right" }, 
        { map = "5,29", changeMap = "right" }, 
        { map = "6,29", changeMap = "right" }, 
        { map = "4,27", changeMap = "bottom" }, 
        { map = "4,28", changeMap = "bottom" }, 
        { map = "7,29", changeMap = "bottom" }, 
        { map = "7,30", changeMap = "right" }, 
        { map = "8,30", changeMap = "right" }, 
        { map = "9,30", changeMap = "right" }, 
        { map = "10,30", changeMap = "top" }, 
        { map = "10,29", changeMap = "right" }, 
        { map = "11,29", changeMap = "right" }, 
        { map = "12,29", changeMap = "right" }, 
        { map = "13,29", changeMap = "right" }, 
        { map = "14,29", changeMap = "top" }, 
        { map = "14,28", changeMap = "left" }, 
        { map = "13,27", changeMap = "left" }, 
        { map = "13,28", changeMap = "top" }, 
        { map = "12,27", changeMap = "top" }, 
        { map = "12,26", changeMap = "right" }, 
        { map = "13,26", changeMap = "right" }, 
        { map = "14,26", changeMap = "top" }, 
        { map = "14,25", changeMap = "right" }, 
        { map = "15,25", changeMap = "top" }, 
        { map = "15,24", changeMap = "top" }, 
        { map = "16,23", changeMap = "top" }, 
        { map = "15,23", changeMap = "right" }, 
        { map = "16,22", changeMap = "left" }, 
        { map = "15,22", changeMap = "left" }, 
        { map = "14,22", changeMap = "left" }, 
        { map = "13,22", changeMap = "left" }, 
        { map = "12,22", changeMap = "left" }, 
        { map = "11,22", changeMap = "left" }, 
        { map = "10,22", changeMap = "top" }, 
        { map = "10,21", changeMap = "top" }, 
        { map = "10,20", changeMap = "left" }, 
        { map = "9,20", changeMap = "left" }, 
        { map = "8,19", changeMap = "left" }, 
        { map = "7,18", changeMap = "left" }, 
        { map = "6,18", changeMap = "left" }, 
        { map = "8,20", changeMap = "top" }, 
        { map = "7,19", changeMap = "top" }, 
        { map = "5,18", changeMap = "top" }, 
        { map = "5,17", changeMap = "top" }, 
        { map = "5,16", changeMap = "top" }, 
        { map = "5,15", changeMap = "top" }, 
        { map = "5,14", changeMap = "left" }, 
        { map = "4,14", changeMap = "left" }, 
        { map = "3,14", changeMap = "left" }, 
        { map = "2,14", changeMap = "left" }, 
        { map = "1,14", changeMap = "left" }, 
        { map = "0,14", changeMap = "left" }, 
        { map = "-1,14", changeMap = "top" }, 
        { map = "-1,13", changeMap = "top" }, 
        { map = "-1,12", changeMap = "right" }, 
        { map = "0,12", changeMap = "top" }, 
        { map = "0,11", changeMap = "right" }, 
        { map = "1,11", changeMap = "right" }, 
        { map = "2,11", changeMap = "right" }, 
        { map = "3,11", changeMap = "right" }, 
        { map = "4,11", changeMap = "right" }, 
        { map = "5,11", changeMap = "top" }, 
        { map = "5,10", changeMap = "top" }, 
        { map = "5,9", changeMap = "top" }, 
        { map = "5,8", changeMap = "top" }, 
        { map = "5,7", changeMap = "top" }, 
        { map = "5,6", changeMap = "top" }, 
        { map = "5,5", changeMap = "top" }, 
        { map = "5,4", changeMap = "top" }, 
        { map = "5,3", changeMap = "top" }, 
        { map = "5,2", changeMap = "left" }, 
        { map = "4,2", changeMap = "left" }, 
        { map = "3,2", changeMap = "top" }, 
        { map = "3,1", changeMap = "left" }, 
        { map = "2,1", changeMap = "left" }, 
        { map = "1,1", changeMap = "left" }, 
        { map = "0,1", changeMap = "left" }, 
        { map = "-1,1", changeMap = "left" }, 
        { map = "-2,1", changeMap = "top" }, 
        { map = "-2,0", changeMap = "right" }, 
        { map = "-1,0", changeMap = "right" }, 
        { map = "0,0", changeMap = "right" }, 
        { map = "1,0", changeMap = "right" }, 
        { map = "2,0", changeMap = "right" }, 
        { map = "3,0", changeMap = "top" }, 
        { map = "3,-1", changeMap = "top" }, 
        { map = "5,-2", changeMap = "top" }, 
        { map = "3,-2", changeMap = "right" }, 
        { map = "4,-2", changeMap = "right" }, 
        { map = "5,-3", changeMap = "right" }, 
        { map = "6,-3", changeMap = "right" }, 
        { map = "7,-3", changeMap = "top" }, 
        { map = "8,-4", changeMap = "top" }, 
        { map = "8,-5", changeMap = "top" }, 
        { map = "7,-4", changeMap = "right" }, 
        { map = "8,-6", changeMap = "left" }, 
        { map = "7,-6", changeMap = "left" }, 
        { map = "6,-6", changeMap = "left" }, 
        { map = "5,-6", changeMap = "bottom" }, 
        { map = "5,-5", changeMap = "left" }, 
        { map = "4,-5", changeMap = "left" }, 
        { map = "3,-5", changeMap = "top" }, 
        { map = "3,-6", changeMap = "right" }, 
        { map = "4,-6", changeMap = "top" }, 
        { map = "4,-7", changeMap = "top" }, 
        { map = "4,-8", changeMap = "left" }, 
        { map = "4,-9", changeMap = "top" }, 
        { map = "3,-10", changeMap = "left" }, 
        { map = "2,-10", changeMap = "left" }, 
        { map = "1,-10", changeMap = "left" }, 
        { map = "0,-10", changeMap = "left" }, 
        { map = "-1,-10", changeMap = "left" }, 
        { map = "-2,-10", changeMap = "left" }, 
        { map = "-3,-10", changeMap = "bottom" }, 
        { map = "-3,-9", changeMap = "bottom" }, 
        { map = "-3,-8", changeMap = "left" }, 
        { map = "-4,-8", changeMap = "left" }, 
        { map = "-22,27", changeMap = "bottom" }, 
        { map = "-22,28", changeMap = "left" }, 
        { map = "-23,28", changeMap = "left" }, 
        { map = "-11,24", changeMap = "right" }, 
        { map = "-9,25", changeMap = "bottom" }, 
        { map = "4,-10", changeMap = "left" }, 
        { map = "-24,-56", changeMap = "top" }, 
        { map = "-24,-57", changeMap = "top" }, 
        { map = "-24,-58", changeMap = "top" }, 
        { map = "-24,-59", changeMap = "left" }, 
        { map = "-25,-59", changeMap = "top" }, 
        { map = "-25,-60", changeMap = "top" }, 
        { map = "-25,-61", changeMap = "top" }, 
        { map = "-25,-62", changeMap = "left" }, 
        { map = "-26,-62", changeMap = "left" }, 
        { map = "-27,-62", changeMap = "left" }, 
        { map = "-28,-62", changeMap = "left" }, 
        { map = "-30,-60", changeMap = "bottom" }, 
        { map = "-30,-59", changeMap = "bottom" }, 
        { map = "-30,-55", changeMap = "bottom" }, 
        { map = "-30,-54", changeMap = "bottom" }, 
        { map = "-30,-53", changeMap = "right" }, 
        { map = "-29,-53", changeMap = "bottom" }, 
        { map = "-29,-52", changeMap = "right" }, 
        { map = "-28,-52", changeMap = "bottom" }, 
        { map = "-28,-51", changeMap = "right" }, 
        { map = "-27,-51", changeMap = "right" }, 
        { map = "-26,-51", changeMap = "bottom" }, 
        { map = "-26,-50", changeMap = "right" }, 
        { map = "-25,-50", changeMap = "bottom" }, 
        { map = "-29,-61", changeMap = "left" }, 
        { map = "-29,-62", changeMap = "bottom" }, 
        { map = "-25,-49", changeMap = "bottom" }, 
        { map = "-25,-48", changeMap = "left" }, 
        { map = "-26,-48", changeMap = "left" }, 
        { map = "-27,-48", changeMap = "left" }, 
        { map = "-28,-48", changeMap = "left" }, 
        { map = "-30,-58", changeMap = "left" }, 
        { map = "-31,-58", changeMap = "bottom" }, 
        { map = "-31,-57", changeMap = "bottom" }, 
        { map = "-31,-56", changeMap = "bottom" }, 
        { map = "-31,-55", changeMap = "right" }, 
        { map = "-26,31", changeMap = "bottom" }, 
        { map = "-26,32", changeMap = "bottom" }, 
        { map = "-26,33", changeMap = "bottom" }, 
        { map = "-26,34", changeMap = "bottom" }, 
        { map = "-26,35", changeMap = "bottom" }, 
        { map = "-26,36", changeMap = "bottom" }, 
        { map = "-20,20", changeMap = "bottom" }, 
        { map = "-20,21", changeMap = "bottom" }, 
        { map = "-20,22", changeMap = "bottom" }, 
        { map = "-25,12", changeMap = "bottom" }, 
        { map = "-18,36", changeMap = "top" }, 
        { map = "-18,35", changeMap = "top" }, 
        { map = "-18,34", changeMap = "top" }, 
        { map = "-18,33", changeMap = "top" }, 
        { map = "-19,36", changeMap = "right" }, 
        { map = "-19,37", changeMap = "top" }, 
        { map = "-21,36", changeMap = "right" }, 
        { map = "-22,36", changeMap = "right" }, 
        { map = "-23,36", changeMap = "right" }, 
        { map = "-26,37", changeMap = "right" }, 
        { map = "-25,37", changeMap = "bottom" }, 
        { map = "-25,38", changeMap = "right" }, 
        { map = "-24,38", custom = brakmarr() }, 
        { map = "-23,38", custom = brakmarrr() }, 
        { map = "-23,37", changeMap = "top" }, 
        { map = "-18,32", changeMap = "top" }, 
        { map = "-18,31", changeMap = "top" }, 
        { map = "-18,30", changeMap = "top" }, 
        { map = "-18,29", changeMap = "top" }, 
        { map = "-18,28", changeMap = "top" }, 
        { map = "-18,27", changeMap = "top" }, 
        { map = "-18,26", changeMap = "top" }, 
        { map = "-18,25", changeMap = "top" }, 
        { map = "-18,24", changeMap = "top" }, 
        { map = "-20,23", changeMap = "bottom" }, 
    }
end


function bank()
	return {
		{map = "191104002", changeMap = "261"}, --Devant banque Astrub--
		{map = "192415750", changeMap = "409"}, --Banque Astrub--
		{map = "54172457", changeMap = "344"}, --Devant banque Frigost--
		{map = "54534165", changeMap = "424", npcBank = true}, --Banque Frigost--
		{map = "147254", changeMap = "283"}, --Devant banque Bonta--
		{map = "2883593", changeMap = "409", npcBank = true}, --Banque Bonta--
		{map = "88081177", changeMap = "203"}, --Devant banque Amakna--
		{map = "99095051", changeMap = "410", npcBank = true}, --Banque Amakna--
		{map = "144931", changeMap = "248"}, --Devant banque Brakmar--
		{map = "8912911", changeMap = "424", npcBank = true}, --Banque Brakmar--
		{map = "90703872", changeMap = "302"}, --Devant banque Sufokia --
		{map = "91753985", changeMap = "494", npcBank = true}, --Banque Sufokia--
		{map = "155157", changeMap = "342"}, --Devant banque Ottomaï--
		{map = "86511105", changeMap = "452", npcBank = true}, --Banque Ottomaï--
		{map = "12580", changeMap = "242"}, --Devant banque Pandala--
		{map = "8129542", changeMap = "409", npcBank = true}, --Banque Pandala--
		{map = "73400323", changeMap = "330"}, --Devant banque Montagne Koalak--
		{map = "84935175", changeMap = "425", npcBank = true}, --Banque Montagne Koalak--
	}
end


function phenix()
	return {
	}
end

function lost()
	global:printMessage("Careful, your bot got lost on "..map:currentPos().." / "..tostring(map:currentMapId()))
end



